controller_list:
  - name: fake_roboarm_kin_controller
    type: $(arg fake_execution_type)
    joints:
      - base_link__waist_link
      - waist_link__arm1_link
      - arm1_link__arm2_link
      - arm2_link__arm3_link
      - arm3_link__gb_link
  - name: fake_roboarm_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - arm3_link__gb_link
initial:  # Define initial robot poses per group
  - group: roboarm_kin
    pose: home