arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_link__waist_link
    - waist_link__arm1_link
    - arm1_link__arm2_link
    - arm2_link__arm3_link
    - arm3_link__gb_link
  gains:
    base_link__waist_link:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    waist_link__arm1_link:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_link__arm2_link:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_link__arm3_link:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm3_link__gb_link:
      p: 100
      d: 1
      i: 1
      i_clamp: 1